[versions]
kotlin = "2.0.21"
kotlinxDatetime = "0.6.2"
kotlinxSerializationJSON = "1.8.1"
kotlinxCoroutines = "1.10.2"

# Библиотеки для DI и БД
koin = "3.5.0"
exposed = "0.48.0"
hikariCP = "5.0.1" # Пул соединений для БД
postgresql = "42.7.3" # Драйвер PostgreSQL (или h2 для in-memory)

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

# Koin для DI
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# Exposed для работы с БД
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" } # Для работы с датами
exposed-kotlin-datetime = { group = "org.jetbrains.exposed", name = "exposed-kotlin-datetime", version.ref = "exposed" }

# Пул соединений и драйвер БД
hikariCP = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikariCP" }
postgresql-driver = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Для тестирования
#koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
#junit-jupiter = "org.junit.jupiter:junit-jupiter:5.11.3"

# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines-core", "kotlinxCoroutines-test"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#kotlkotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }